yoav - Rollers joystick commands
GreenBlitz/CRRRRESCENDO pull request #101
Opened 2024-02-08 18:32 UTC by bossyshrimp68

dont merge until funnel and roller ocmmand merged!!!

2024-02-08 18:52 UTC, tnrz135 approved these changes

2024-02-09 20:58 UTC, yonnbro requested changes
Add a third and forth debug controllers and assign a joystick to each one

2024-02-10 14:22 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/OI.java
> +        //initButtons();
Why comment initbuttons and defaultcommands?

2024-02-10 15:27 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/OI.java
> +        //initButtons();
I meant leave the “official” controls and just add the new joysticks

2024-02-10 15:37 UTC, yonnbro approved these changes

2024-02-10 16:05 UTC, merged

2024-02-10 16:20 UTC, yonnbro commented
Test master!