Lifter solenoid
GreenBlitz/CRRRRESCENDO pull request #108
Opened 2024-02-10 21:25 UTC by greenblitz4590

2024-02-10 22:03 UTC, bossyshrimp68 requested changes

2024-02-10 22:03 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/LifterSolenoid/SimulationLifterSolenoid/SimulationLifterSolenoid.java
> +	}
space

2024-02-10 22:03 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/LifterSolenoid/SimulationLifterSolenoid/SimulationLifterSolenoidConstants.java
> +	public static final int MOTOR_NUM = 1;
```suggestion
	public static final int NUMBER_OF_MOTORS = 1;
```

2024-02-12 18:26 UTC, yonnbro requested changes

2024-02-12 18:26 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/OI.java
> +//        SwerveChassis.getInstance().setDefaultCommand(new MoveByJoysticks(DRIVE_MODE));
Don’t comment out controls in master!!

2024-02-12 18:26 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/commands/Climb/lifter/ExtendLifter.java
> +//            lifter.goToPosition(LifterConstants.LIFTER_EXTENDED_POSITION);
Why?

2024-02-12 18:26 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/commands/Climb/lifter/ExtendLifter.java
> +//        return lifter.isAtPosition(LifterConstants.LIFTER_EXTENDED_POSITION);
What? Delete comments if not real, but are you sure the command will never finish?

2024-02-12 18:26 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/NeoLifter/NeoLifterConstants.java
> +    public static final boolean IS_BACKWARD_LIMIT_SWITCH_ENABLED = false;
Why false???

2024-02-12 18:26 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/LifterSolenoid/RealLifterSolenoid/RealLifterSolenoidConstants.java
> +	public static final int SOLENOID_ID = 6;
No real hold voltage, no power to hold, no power to open, no power to close

2024-02-12 18:26 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/LifterSolenoid/LifterSolenoidConstants.java
> +
Wich const class are you using? This or realliftersolonoid?

2024-02-13 12:23 UTC, closed without merging