Shooting Improvement
GreenBlitz/CRRRRESCENDO pull request #117
Opened 2024-02-11 20:30 UTC by YoniKiriaty

Fixed issue with shooting where it would shoot at bad angles and put an ugly fix on an issue with pathplanner where it doesn't move if it's 0.5 meters apart from its target position.

This is temporary until better ways are found or made.

2024-02-11 20:30 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBPathFindHolonomic.java
exactly the same as the wpilib Autobuilder but has a paramater for the translational tolerance

2024-02-11 20:31 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBAutoBuilder.java
exactly the same as the wpilib Autobuilder but has a paramater for the translational tolerance

2024-02-11 20:32 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBPathfindingCommand.java
exactly the same as the PathPlanner PathFindingCommand but has a paramater for the translational tolerance

2024-02-11 20:42 UTC, bossyshrimp68 requested changes

2024-02-11 20:42 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +                ChassisConstants.TRANSLATIONAL_TOLERANCE,
add one for the rotational as well

2024-02-11 20:55 UTC, bossyshrimp68 approved these changes

2024-02-12 11:35 UTC, bossyshrimp68 approved these changes

2024-02-12 13:55 UTC, yonnbro commented
Why do we copy so much code from PP? Why not inherit from the PathPlanning Command and just overiding the initialize function?

2024-02-12 14:06 UTC, YoniKiriaty commented
> Why do we copy so much code from PP? Why not inherit from the PathPlanning Command and just overiding the initialize function?

The objects used in the path planning command are private, so you can not access them from inside the overridden initialize.

2024-02-12 15:06 UTC, bossyshrimp68 approved these changes

2024-02-12 15:26 UTC, merged