Shooting zones
GreenBlitz/CRRRRESCENDO pull request #123
Opened 2024-02-12 19:16 UTC by YoniKiriaty

2024-02-13 12:46 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/Pivot.java
> +import edu.greenblitz.robotName.subsystems.shooter.pivot.PivotConstants;
Why?

2024-02-13 12:52 UTC, yonnbro reviewed
I need an explanation about what is shooting zone and the wrapper zone

2024-02-13 14:05 UTC, YoniKiriaty commented
> I need an explanation about what is shooting zone and the wrapper zone

The problem was that if the robot was too close to it's shooting zone position it would not move to it because of pathplanner 🙄.
The way it is fixed is by making a wrapper zone around a small zone, which if the robot is inside it it would behave how it should be when it is used inside a zone, but if it is outside the wrapper zone it tries to go the the bound of the optimal zone, which is included inside the wrapper zone. Also the shooting zone was made so it is not a full circle but a specific portion determined by an angle:
![quarter circle](https://github.com/GreenBlitz/CRRRRESCENDO/assets/139997639/f9c0c32e-df6b-4870-8d92-62e6144afe17)

The close shooting zone is for the possibility that we can't shoot too far/consistent enough.

2024-02-13 14:21 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
> +    public static final double LEGAL_SHOOTING_ZONE_RADIUS_IN_METERS = 3;
Make the legal radius const “bound” to the optimal radius const

2024-02-13 14:22 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
> +    public static final double LEGAL_SHOOTING_ZONE_RADIUS_IN_METERS = 3;
So just by changing the optimal radius the legal radius updates as well

2024-02-13 14:22 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
> +    public static final double LEGAL_SHOOTING_ZONE_RADIUS_IN_METERS = 3;
(Doesnt have to be at runtime, consts are good

2024-02-13 14:25 UTC, YoniKiriaty commented
I went for a different implementation that doesnt use the wrapper because its simpler and has no issues.
now if its too close it goes to the middle of the shooting zone

2024-02-13 14:28 UTC, yonnbro commented
> I realized i could go for a different implementation that doesnt use the wrapper because its simpler and has no issues.
> now if its too close it goes to the middle of the shooting zone

Please talk to us before changing things we agreed on… I really really don’t like this behavior… it will create unexpected long chassis for the driver, the previous solution is better IMO

2024-02-13 14:36 UTC, YoniKiriaty commented
> > I realized i could go for a different implementation that doesnt use the wrapper because its simpler and has no issues.
> > now if its too close it goes to the middle of the shooting zone
> 
> Please talk to us before changing things we agreed on… I really really don’t like this behavior… it will create unexpected long chassis movements for the driver, the previous solution is better IMO

ok

2024-02-13 15:50 UTC, yonnbro approved these changes

2024-02-13 17:11 UTC, NoamRosenberg08 requested changes

2024-02-13 17:11 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootFromCloseRange.java
> +public class ShootFromCloseRange extends GoToShootingStateAndShoot {
i think that it is not needed

2024-02-13 17:11 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
> +    public static final Rotation2d LEGAL_LOWER_ANGLE_LIMIT = Rotation2d.fromDegrees(-50);
why in negative numbers, please convert to positive

2024-02-14 14:50 UTC, bossyshrimp68 requested changes

2024-02-14 14:50 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
> +    public static final double OPTIMAL_SHOOTING_ZONE_RADIUS_IN_METERS = 2.5;
spaces

2024-02-14 14:50 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingStateCalculations.java
> +        if (closestPosition.getDistance(getRobotPose().getTranslation()) > SwerveChassis.TRANSLATION_TOLERANCE &&
add {

2024-02-14 17:31 UTC, bossyshrimp68 approved these changes

2024-02-14 17:32 UTC, bossyshrimp68 approved these changes

2024-02-14 17:33 UTC, merged