Note simulation
GreenBlitz/CRRRRESCENDO pull request #125
Opened 2024-02-13 18:52 UTC by YoniKiriaty

2024-02-14 14:57 UTC, bossyshrimp68 requested changes

2024-02-14 14:57 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +		thirdJoystickButtons();
delete

2024-02-14 14:57 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/PushNoteToFlyWheel.java
> +                new StopFlyWheel().alongWith(new ShootSimulationNote())
shouldnt be here

2024-02-14 14:57 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/ShootSimulationNote.java
> +                });
```suggestion
                }
        );
```

2024-02-14 14:57 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
> +                new Rotation3d(0,0,swervePose2d.getRotation().getRadians())
add spaces

2024-02-14 17:30 UTC, bossyshrimp68 requested changes

2024-02-14 17:30 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
> +                new Translation3d(swervePose2d.getX(), swervePose2d.getY(), RobotConstants.SimulationConstants.ROBOT_TRANSLATION.getZ()),
spaces

2024-02-14 18:07 UTC, bossyshrimp68 approved these changes

2024-02-14 18:12 UTC, bossyshrimp68 approved these changes

2024-02-15 17:45 UTC, yonnbro requested changes

2024-02-15 17:45 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBAutoBuilder.java
Empty file?

2024-02-15 17:45 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/OI.java
> +		usedJoystick.Y.whileTrue(new ShootSimulationNote());
Use 4th controller

2024-02-15 17:45 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/RobotConstants.java
> -		public static final Translation3d ARM_TO_ROBOT = new Translation3d(0, 0, 1.2);
Is this not being used?

2024-02-15 17:45 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
> +	public static final double SHOOTING_SPEED_TIME = -1;
What? Also add units to var name

2024-02-15 17:45 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBAutoBuilder.java
This file is empty

2024-02-16 00:05 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/RobotConstants.java
> -		public static final Translation3d ARM_TO_ROBOT = new Translation3d(0, 0, 1.2);
No it is not

2024-02-17 14:18 UTC, yonnbro approved these changes

2024-02-17 15:18 UTC, merged