Chassis intake
GreenBlitz/CRRRRESCENDO pull request #13
Opened 2024-01-18 19:45 UTC by greenblitz4590

2024-01-18 21:36 UTC, tnrz135 requested changes
A general comment:
Why the name ChassisIntake and not simply Intake? It doesn't use the chassis in the code (or something like that)

2024-01-21 15:10 UTC, hillelv requested changes
Romy, i am natzier than raz

2024-01-21 15:10 UTC, hillelv commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/Intake.java
> +	public Intake getInstance() {
```suggestion
	public static Intake getInstance() {
		init();
		return instance;
	}

	public static void init(){
		if (instance == null) {
			instance = new Intake();
		}
	}
```

2024-01-21 15:10 UTC, hillelv commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/IntakeConstants.java
> +	public static final PIDController MOTOR_PID_P = new PIDController(0, 0, 0);
P?

2024-01-21 15:10 UTC, hillelv commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/RealIntake.java
> +public class RealIntake implements IIntake {
change to neo

2024-01-21 15:29 UTC, tnrz135 approved these changes

2024-01-21 15:31 UTC, merged