Calibration
GreenBlitz/CRRRRESCENDO pull request #138
Opened 2024-02-20 16:51 UTC by greenblitz4590

2024-02-20 17:09 UTC, NoamRosenberg08 requested changes

2024-02-20 17:09 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/intake/neoIntake/NeoIntakeConstants.java
> +	public static final int INTAKE_ID = 3;
rename to motor id

2024-02-20 17:09 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
> +						.withLimitReverseMotion(false)
shouldnt it be true

2024-02-20 17:55 UTC, yonnbro requested changes

2024-02-20 17:55 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/MovePivotToAngle.java
> +import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
unused import

2024-02-20 17:55 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheelConstants.java
> +		public static final int ID = 16;
change name to MOTOR_ID to follow convention

2024-02-20 17:55 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheelConstants.java
> +		public static final String CANBUS_CHAIN = "";
not connected to canivore?

2024-02-20 17:55 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/neoFunnel/NeoFunnel.java
> +		inputs.isObjectIn = debouncer.calculate(motor.getReverseLimitSwitch(SparkMaxLimitSwitch.Type.kNormallyOpen).isLimitSwitchEnabled());
test to see if this also updates the `this.isObjectIn`

2024-02-20 17:55 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
> +		getAbsoluteEncoderPosition();
delete

2024-02-20 17:55 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
> +		resetAngle(getAbsoluteEncoderPosition());
not here

2024-02-20 17:55 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
> +		SmartDashboard.putNumber("abs pos", inputs.absoluteEncoderPosition.getDegrees());
remove

2024-02-20 18:54 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/neoFunnel/NeoFunnel.java
> +		inputs.isObjectIn = debouncer.calculate(motor.getReverseLimitSwitch(SparkMaxLimitSwitch.Type.kNormallyOpen).isLimitSwitchEnabled());
ok

2024-02-20 18:54 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheelConstants.java
> +		public static final String CANBUS_CHAIN = "";
mo

2024-02-20 19:42 UTC, yonnbro approved these changes

2024-02-21 10:09 UTC, yonnbro requested changes

2024-02-21 10:09 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/neoFunnel/NeoFunnel.java
> +		SmartDashboard.putBoolean("funnel",inputs.isObjectIn);
No no no no

2024-02-21 23:05 UTC, bossyshrimp68 requested changes

2024-02-21 23:05 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/intake/neoIntake/NeoIntake.java
> +//		intakeInputs.exitBeamBreakerValue = exitBeamBreaker.calculate(
a lot of comments here, delete if really or used or uncomment

2024-02-21 23:05 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +//		AutonomousSelector.getInstance().getChosenValue().schedule();
uncomment

2024-02-22 11:46 UTC, yonnbro approved these changes

2024-02-22 19:18 UTC, bossyshrimp68 requested changes

2024-02-23 16:15 UTC, bossyshrimp68 requested changes

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +				new RunCommand(() -> frontLeft.rotateToAngle(Rotation2d.fromDegrees(90))));
huh?

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +//		initializeDefaultCommands();
dont mark it resolved if its not..

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +				0.3,
magic..

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +//		mainJoystick.A.whileTrue(new GoToShootingState(ShootingPositionConstants.OPTIMAL_SHOOTING_ZONE));
give back...

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +//		Pivot.getInstance().setDefaultCommand(new PivotDefaultCommand());
stop resolving and not solving..

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Robot.java
so much commented out code

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/NoteToShooter.java
> +        SmartDashboard.putNumber("SS", 1);
delete

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/NoteToShooter.java
> +        if (timer.get() > FunnelConstants.NOTE_TO_SHOOTER_DELAY_TIME)
add {

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
> +		SmartDashboard.putNumber("pivit angle abs", inputs.absoluteEncoderPosition.getDegrees());
dym abs like absurd or abstract?

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivotConstants.java
> +
delete

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivotConstants.java
> +	static {
add a space

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivotConstants.java
>  	public static final TalonFXConfiguration TALON_FX_CONFIGURATION = new TalonFXConfiguration();
add a space

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4iSwerveConstants.java
> +
delete space

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4iSwerveConstants.java
> +		PID_CONFIGS.kP = 0;//70;
//70?

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4iSwerveConstants.java
> +		PID_CONFIGS.kS = ks;
why is only the ks = ks?

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalconConstants.java
> +    }
SROP RSOLVING AND NOT SOLVING, and why is it empty

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalconConstants.java
> +    }
same here

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalconConstants.java
> +    public static final FeedbackConfigs FEEDBACK_CONFIGS = new FeedbackConfigs();
add a space means to the line right under my comment

2024-02-23 16:15 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalconConstants.java
> +
delete space

2024-02-23 17:10 UTC, yonnbro approved these changes

2024-02-23 18:55 UTC, bossyshrimp68 approved these changes

2024-02-23 18:58 UTC, bossyshrimp68 approved these changes

2024-02-23 19:03 UTC, bossyshrimp68 approved these changes

2024-02-23 19:03 UTC, merged