yoav - bag wrist
GreenBlitz/CRRRRESCENDO pull request #139
Opened 2024-02-20 20:46 UTC by hillelv

2024-02-22 09:05 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/utils/Conversions.java
> +			return angle.getRotations() * 4096.0;
Maybe make a constant for this `4096.0`

2024-02-23 18:43 UTC, yonnbro approved these changes

2024-02-23 23:16 UTC, yonnbro commented
Can you also rename to SRX or BrushedMotorWrist?

2024-02-24 09:48 UTC, yonnbro approved these changes

2024-02-24 18:47 UTC, bossyshrimp68 requested changes

2024-02-24 18:47 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/srxWrist/SRXWrist.java
> +        motor.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Absolute, SRXWristConstants.PID_SLOT, SRXWristConstants.TIMEOUT_FOR_CONFIG_SET);
```suggestion
        motor.configSelectedFeedbackSensor(
               FeedbackDevice.CTRE_MagEncoder_Absolute, 
               SRXWristConstants.PID_SLOT, SRXWristConstants.TIMEOUT_FOR_CONFIG_SET
        );
```

2024-02-24 18:47 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/srxWrist/SRXWrist.java
> +        motor.set(TalonSRXControlMode.PercentOutput, voltage / 12);
magic num

2024-02-24 18:47 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/srxWrist/SRXWristConstants.java
> +    public static final TalonSRXConfiguration TALON_SRX_CONFIGURATION = new TalonSRXConfiguration();
add a space and delete the ones in the bottom

2024-02-24 19:27 UTC, bossyshrimp68 requested changes

2024-02-24 19:27 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/srxWrist/SRXWrist.java
> +    public SRXWrist(){
```suggestion
    public SRXWrist() {
```

2024-02-24 19:30 UTC, bossyshrimp68 approved these changes

2024-02-24 19:30 UTC, merged