yoav - fixing gyro
GreenBlitz/CRRRRESCENDO pull request #147
Opened 2024-02-23 18:03 UTC by aaa-png

2024-02-23 18:28 UTC, yonnbro approved these changes

2024-02-23 18:28 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/gyros/Pigeon2Gyro.java
> +		inputs.yaw = (Units.degreesToRadians(pigeon2.getYaw().getValue()) - yawOffset.getRadians()) % (2 * Math.PI);
Put 2 * Math.PI in const

2024-02-24 10:38 UTC, bossyshrimp68 requested changes

2024-02-24 10:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/gyros/Pigeon2Gyro.java
> +		pigeon2.setYaw(yaw.getDegrees());
why is this setYaw and the rest offset?

2024-02-24 10:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/gyros/Pigeon2Gyro.java
> +		inputs.yaw = (Units.degreesToRadians(pigeon2.getYaw().getValue()) - yawOffset.getRadians()) % GyroConstants.CIRCLE_CIRCUMFRENCE.getRadians();
why..? this is unneeded, the previous version was fine just keep the Units.degToRad like you did here because its more informative

2024-02-24 10:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/gyros/GyroConstants.java
> +    public static final Rotation2d CIRCLE_CIRCUMFRENCE = Rotation2d.fromRadians(2 * Math.PI);
why do you need this and why here?

2024-02-24 19:38 UTC, bossyshrimp68 approved these changes

2024-02-24 19:48 UTC, bossyshrimp68 approved these changes

2024-02-24 19:48 UTC, merged