yoav ,yoni - Calibrate arm
GreenBlitz/CRRRRESCENDO pull request #153
Opened 2024-02-25 21:37 UTC by greenblitz4590

2024-02-25 23:05 UTC, yonnbro requested changes

2024-02-25 23:05 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/bagRoller/BagRoller.java
> +		return Math.abs(current - lastInputs.outputCurrent) >= NeoRollerConstants.NOTE_IN_CURRENT
Is object in is only in one sign (+ for example) and a different sign (- for the same example called isObjectoutByCurrent

2024-02-25 23:05 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/neoRoller/NeoRoller.java
> +        return Math.abs(current - lastInputs.outputCurrent) >= NeoRollerConstants.NOTE_IN_CURRENT
Same as the other comment

2024-02-25 23:05 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/bagFunnel/BagFunnel.java
Why is this here

2024-02-25 23:13 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/OI.java
it is what it is

2024-02-25 23:13 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/OI.java
no its because of ctrl+alt+L ing the file

2024-02-25 23:48 UTC, yonnbro requested changes

2024-02-25 23:48 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/neoRoller/NeoRoller.java
> +        return current - lastInputs.outputCurrent >= NeoRollerConstants.NOTE_IN_CURRENT_JUMP
We need to filter out the motor start current (a short spike in current) maybe a low cut filter, or debouncer or a flag for after the roller reach cruise velocity and only if the rollers are close to the setpoint and the current spikes then consider it object in

2024-02-26 08:35 UTC, bossyshrimp68 requested changes

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +//		initializeDefaultCommands();
...........................................

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Robot.java
//.................................................

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/arm/elbow/ResetElbow.java
> +        elbow.setMotorVoltage(0.5);
magic-

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/arm/elbow/ResetElbow.java
> +        return elbow.getCurrent() > 15;
number

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/arm/elbow/ResetElbow.java
> +        elbow.setPower(0);
dont we have a stop func?

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/Elbow.java
> +        System.out.println(elbowInputs.outputCurrent);
delete print

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/Elbow.java
> +
delete space

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/bagRoller/BagRoller.java
> +		setPower(voltage / Battery.getInstance().getCurrentVoltage());
do we need to do this?

2024-02-26 08:35 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerFactory.java
> +            case SYNCOPA -> new BagRoller();
isnt it neo?

2024-02-26 08:39 UTC, aaa-png requested changes

2024-02-26 08:39 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/Elbow.java
> +        System.out.println(elbowInputs.outputCurrent);
delete

2024-02-26 09:37 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerFactory.java
> +            case SYNCOPA -> new BagRoller();
no

2024-02-26 10:13 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerFactory.java
> +            case SYNCOPA -> new BagRoller();
Wait why no?

2024-03-02 15:44 UTC, closed without merging