Dis 2
GreenBlitz/CRRRRESCENDO pull request #166
Opened 2024-03-01 11:48 UTC by YoniKiriaty

2024-03-01 14:12 UTC, bossyshrimp68 requested changes

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByVelocityWithoutIsFinished.java
> +public class RunFlyWheelByVelocityWithoutIsFinished extends FlyWheelCommand {
```suggestion
public class RunFlyWheelByVelocityUntilInterrupted extends FlyWheelCommand {
```

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/Elbow.java
> +        currentAngle = NeoElbowConstants.MINIMUM_ANGLE;
why?

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/Elbow.java
> +    }
add a space

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/neoElbow/NeoElbow.java
> +        if (targetAngle.getDegrees() <= ElbowConstants.BACKWARD_ANGLE_LIMIT.getDegrees()){
what aout forward limit?

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/neoElbow/NeoElbowConstants.java
> +            .withIdleMode(CANSparkMax.IdleMode.kCoast)
why?

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterConstants.java
> +    public static final double POWER_TO_CLOSE_SOLENOID = 1;
are we sure about this?

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/lifter/neoLifter/NeoLifterConstants.java
>      public static final boolean IS_BACKWARD_LIMIT_SWITCH_ENABLED = true;
give the space back

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelInputs.java
> +	public double leftVelocityReferance;
sapces

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +		mainJoystick.R1.whileTrue(new NoteToShooter());
isnt this also from gorund? consider re-naming

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/neoFunnel/NeoFunnelConstants.java
> +			.withVelocityConversionFactor(1 /9.0);
give the space back

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivotConstants.java
> +
delete

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
> +//		updatePoseEstimationLimeLight();
...

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
> +				new Pose2d(),
i am pretty sure we fixed that already, didnt we?

2024-03-01 14:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/utils/AutonomousSelector.java
> +        chooser.addOption("playoffsgame", new ShootToSpeakerFromClose());
no

2024-03-01 16:38 UTC, bossyshrimp68 requested changes

2024-03-01 16:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +//        NamedCommands.registerCommand("grip", new NoteToShooter());
...

2024-03-01 16:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/arm/elbow/SafeMoveElbowToAngle.java
> +        elbow.moveToAngle(targetAngle);
add a tab

2024-03-01 16:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/utils/AutonomousSelector.java
> +        chooser.addOption("auto", AutoBuilder.buildAuto("2 to 1 close"));
remove

2024-03-02 13:49 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/commands/arm/elbow/SafeMoveElbowToAngle.java
> +            isElbowCrashableIntoWall = true;
Relocate this assignment to the condition itself and not in a void function

2024-03-02 15:33 UTC, yonnbro approved these changes

2024-03-02 15:41 UTC, bossyshrimp68 approved these changes

2024-03-02 15:41 UTC, merged