Shooter
GreenBlitz/CRRRRESCENDO pull request #17
Opened 2024-01-21 15:57 UTC by greenblitz4590

2024-01-21 22:35 UTC, NoamRosenberg08 requested changes

2024-01-21 22:35 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/MotorFlyWheel/FalconFlyWheel/FalconFlyWheel.java
> +		motor.setControl(new MotionMagicVelocityDutyCycle(
motion magic is not the correct use for it at that case.
the MotionMagicVelocityDutyCycle will generate a profile of velocity every cycle of the motor and this action might slow him down. for this case I recommend using VelocityVoltage

2024-01-21 22:35 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/MotorFlyWheel/MotorFlyWheelConstants.java
> +public class MotorFlyWheelConstants extends edu.greenblitz.robotName.subsystems.shooter.FlyWheel.FlyWheelConstants {
why does the constants class extends another class?-

2024-01-21 22:35 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/MotorFlyWheel/neoFlyWheel/NeoFlyWheel.java
> +        inputs.appliedOutput = motor.getAppliedOutput();
multyply by battery voltage

2024-01-21 22:35 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheel.java
> +        //todo add
why todo? just add the PIDController

2024-01-21 22:35 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelInputs.java
> +    public double velocity;
moreeeee.
temperate and more

2024-01-22 18:38 UTC, bossyshrimp68 requested changes

2024-01-22 18:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/OI.java
> +                }
dont put this in master<3

2024-01-22 18:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +//        SwerveChassis.getInstance().resetAllEncoders();
give them back

2024-01-22 18:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +        SmartDashboard.putNumber("voltage", FlyWheel.getInstance().getVoltage());
not in the periodic

2024-01-22 18:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootByVelocity.java
> +    private int isAtShootingSpeed;
```suggestion
    private int timeInShootingSpeed;
```

2024-01-22 18:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheel.java
> +    public static FlyWheel getInstance() {
add an init function

2024-01-22 18:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
> +    public static final double SHOOTING_SPEED_TIME = 1;
```suggestion
    public static final double TIME_UNTIL_STABLE = 1;
```

2024-01-22 18:38 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelFactory.java
> +            default -> new SimulationFlyWheel();
add a simulation case

2024-01-23 16:13 UTC, itamaroryan requested changes

2024-01-23 16:13 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootByVelocity.java
> +    public boolean isFlywheelAtVelocity() {
Why is this public?

2024-01-23 16:13 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootByVelocity.java
> +        flyWheelCommand.setVelocity(velocity);
Why is the class called flyWheelCommand?

2024-01-23 16:13 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootByVelocity.java
> +        flyWheelCommand.setPreparedToShoot(timeInShootingSpeed > FlyWheelConstants.SHOOTING_SPEED_TIME);
Why is the class called flyWheelCommand?

2024-01-23 16:13 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
Ctrl+Alt+L this file <3

2024-01-23 16:13 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheel.java
> +    public double getCurrent (){
Why is there a white space here :(

2024-01-24 10:55 UTC, bossyshrimp68 requested changes

2024-01-24 10:55 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootByVelocity.java
> +        flyWheel.setPreparedToShoot(timeInShootingSpeed > FlyWheelConstants.SHOOTING_SPEED_TIME);
put in isFinished

2024-01-24 10:55 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootByVelocity.java
> +    }
not supposed to be in the command

2024-01-24 10:55 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/Battery.java
> +	private static final double MIN_VOLTAGE_BATTERY = 0;
dont merge this

2024-01-24 10:55 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheel.java
> +    PIDController pidController;
```suggestion
    private FlywheelSim flyWheelSimulation;
    private double appliedVoltage;
    private PIDController pidController;
```

2024-01-24 10:55 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Modules/SwerveModuleFactory.java
> +            case ROBOT_NAME -> new KazaSwerveModule(module);
give the sds back

2024-01-24 16:14 UTC, itamaroryan approved these changes

2024-01-24 16:24 UTC, bossyshrimp68 approved these changes

2024-01-24 16:26 UTC, merged