hillel & noam - wrote intake commands
GreenBlitz/CRRRRESCENDO pull request #18
Opened 2024-01-21 16:14 UTC by greenblitz4590

2024-01-21 22:19 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/IntakeConstants.java
>  	public static class SimulationConstants {
make SimulationConstants in a different file like in the SwerveModules subsystem

2024-01-22 16:10 UTC, bossyshrimp68 requested changes

2024-01-22 16:10 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/intake/ReverseRunIntake.java
> +        intake.setPower(-IntakeConstants.POWER_TO_RUN);
just save a POWER_TO_EJECT or REVERSE_RUN_POWER

2024-01-22 17:12 UTC, bossyshrimp68 requested changes

2024-01-22 17:12 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/commands/intake/ReverseRunIntake.java
> +        intake.setPower(IntakeConstants.POWER_TO_EJECT);
```suggestion
        intake.setPower(IntakeConstants.POWER_TO_REVERSE_RUN);
```
mb

2024-01-22 17:13 UTC, bossyshrimp68 approved these changes
gg

2024-01-22 17:14 UTC, bossyshrimp68 approved these changes

2024-01-22 18:15 UTC, tnrz135 approved these changes

2024-01-22 18:40 UTC, merged