Pivot to master
GreenBlitz/CRRRRESCENDO pull request #28
Opened 2024-01-22 14:54 UTC by greenblitz4590

2024-01-22 17:53 UTC, tnrz135 requested changes

2024-01-22 17:53 UTC, tnrz135 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +//		Logger.recordOutput("DriveTrain/ModuleStates", getSwerveModuleStates());
.-.

2024-01-22 17:53 UTC, tnrz135 commented on src/main/java/edu/greenblitz/robotName/utils/GBMath.java
> +		return angleInRadians == 0 ? 0 : angleInRadians > 0 ? -Math.PI * 2 + angleInRadians : angleInRadians + Math.PI * 2;
This function is not that clean, especially when the function name is not perfect.

2024-01-22 18:17 UTC, bossyshrimp68 requested changes
great job!

2024-01-22 18:17 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/Pivot/PivotFactory.java
> +            default -> new ReplayPivot();
just make a replay case, and make simulation default

2024-01-22 18:17 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/Pivot/SimulationPivot/SimulationPivot.java
> +    private PIDController controller = SIM_PID.getPIDController();
initialize it in the constructor

2024-01-22 18:17 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/Pivot/SimulationPivot/SimulationPivot.java
> +        appliedVoltage = MathUtil.clamp(voltage, -RobotConstants.SimulationConstants.MAX_MOTOR_VOLTAGE, RobotConstants.SimulationConstants.MAX_MOTOR_VOLTAGE);
just make a MIN_MOTOR_VOLTAGE

2024-01-22 18:17 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/Pivot/SimulationPivot/SimulationPivotConstants.java
> +    public static final PIDObject SIM_PID = new PIDObject().withKp(0.8).withKd(0.3).withMaxPower(1);
DID SOMEONE SAY SIM????

2024-01-22 19:36 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/Pivot/SimulationPivot/SimulationPivot.java
> +        appliedVoltage = MathUtil.clamp(voltage, -RobotConstants.SimulationConstants.MAX_MOTOR_VOLTAGE, RobotConstants.SimulationConstants.MAX_MOTOR_VOLTAGE);
when you merge shooter change it

2024-01-23 15:14 UTC, bossyshrimp68 approved these changes

2024-01-24 11:15 UTC, itamaroryan requested changes
Please Ctrl+Alt+L before pushing the final version of the code <3

2024-01-24 11:15 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/movePivotToAngle/MovePivotToAngle.java
> +	public MovePivotToAngle(double goalAngle, boolean isReal) {
Please change this to `isSimulation` or something like that.

2024-01-24 12:39 UTC, itamaroryan approved these changes

2024-01-24 15:36 UTC, YoniKiriaty approved these changes
Amireeeee

2024-01-24 15:39 UTC, merged