Pose exp comp AKA discretization
GreenBlitz/CRRRRESCENDO pull request #4
Opened 2024-01-11 19:30 UTC by greenblitz4590

2024-01-12 13:01 UTC, tnrz135 approved these changes

2024-01-12 19:59 UTC, NoamRosenberg08 requested changes

2024-01-12 19:59 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +        SwerveChassis.getInstance().setDefaultCommand(new MoveByJoysticks(MoveByJoysticks.DriveMode.SLOW));
if you merge change back to NORMAL

2024-01-12 19:59 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +        SwerveChassis.getInstance().setDefaultCommand(new MoveByJoysticks(MoveByJoysticks.DriveMode.SLOW));
for testing keep it slow

2024-01-12 19:59 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +        if (RobotConstants.ROBOT_TYPE.equals(Robot.RobotType.ROBOT_NAME))
add {} for the if statement

2024-01-12 19:59 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Modules/mk4iSwerveModule/MK4iSwerveConstants.java
> +	public static SwerveModuleConfigObject MK4I_MODULE_BAK_RIGHT = new SwerveModuleConfigObject(12, 5, 3, Rotation2d.fromRotations(0.8718),true);
why did you change the values? you have an MK4I swerve chassis in your basement?

2024-01-12 19:59 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/SwerveChassisUtils.java
>      }
for another pull request. please remove when you merge.

2024-01-16 12:45 UTC, bossyshrimp68 requested changes
amazing and breathtaking (the ", " comment is nazi you dont really need to change)

2024-01-16 12:45 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +    public static void printStates(SwerveModuleState[] states) {
why static

2024-01-16 12:45 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +            System.out.println(states[i].angle + "," + states[i].speedMetersPerSecond);
```suggestion
            System.out.println(states[i].angle + ", " + states[i].speedMetersPerSecond);
```

2024-01-16 12:58 UTC, bossyshrimp68 approved these changes
Romy - good job yoni gg

2024-01-16 17:47 UTC, yonnbro requested changes

2024-01-16 17:47 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +    public void printStates(SwerveModuleState[] states) {
remove debug func

2024-01-16 17:47 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +            timeStep = RoborioUtils.getCurrentRoborioCycle()*REAL_DISCRETION_CONSTANT;
CTRL + ALT + L

2024-01-16 17:48 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +    public void printStates(SwerveModuleState[] states) {
or use it in a dashboard

2024-01-20 16:47 UTC, bossyshrimp68 approved these changes

2024-01-20 17:07 UTC, Stormageddon37 requested changes

2024-01-20 17:07 UTC, Stormageddon37 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/ChassisConstants.java
> +    public static final MoveByJoysticks.DriveMode CURRENT_DRIVE_MODE = MoveByJoysticks.DriveMode.NORMAL;
Why is `CURRENT_DRIVE_MODE` final?

The name implies that this value changes throughout the runtime

2024-01-20 17:07 UTC, Stormageddon37 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +import static edu.greenblitz.robotName.subsystems.swerve.Chassis.ChassisConstants.*;
It is considered a bad practice to `import *`, make sure you really need it

2024-01-20 17:07 UTC, Stormageddon37 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +  	}
CTRL + ALT + L

2024-01-20 17:07 UTC, Stormageddon37 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +    	}
This is a bit of a weird way to handle an enum

2024-01-20 17:07 UTC, Stormageddon37 commented on src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
> +		return TIME_STEP;
Bruh

2024-01-20 18:37 UTC, bossyshrimp68 approved these changes

2024-01-20 18:37 UTC, merged