fixes
GreenBlitz/CRRRRESCENDO pull request #44
Opened 2024-01-26 20:04 UTC by YHerm

removed static in intake and funnel and inserted to simulate and neo package
added init in OI
removed final from sysid

2024-01-27 12:12 UTC, YoniKiriaty requested changes
almost

2024-01-27 12:12 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/OI.java
> +        init();
this is reserved for when clean-master is merged, return it to what it was

2024-01-27 12:12 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +        OI.init();
same here

2024-01-27 12:12 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/IntakeFactory.java
> +			case SIMULATION -> new SimulationIntake();
why is it so far

2024-01-27 12:49 UTC, YoniKiriaty approved these changes

2024-01-27 13:07 UTC, aaa-png approved these changes
UNICODE: 4f000

2024-01-27 15:28 UTC, tnrz135 requested changes

2024-01-27 15:28 UTC, tnrz135 commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/IntakeFactory.java
> +			case SIMULATION -> new SimulationIntake();
Why was it resolved without being fixed

2024-01-27 18:24 UTC, bossyshrimp68 approved these changes

2024-01-28 14:04 UTC, tnrz135 approved these changes

2024-01-28 14:17 UTC, itamaroryan approved these changes
Good stuff

2024-01-28 14:22 UTC, merged

2024-01-30 15:22 UTC, bossyshrimp68 commented
המחליק הוא המצחיק


On Sun, 28 Jan 2024 at 16:22, greenblitz4590 ***@***.***>
wrote:

> Merged #44 <https://github.com/GreenBlitz/CRRRRESCENDO/pull/44> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GreenBlitz/CRRRRESCENDO/pull/44#event-11620076817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3HXEDDS2NRVXQTS5UXV4ZLYQZNJXAVCNFSM6AAAAABCMU7Q3KVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGYZDAMBXGY4DCNY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>