Amir - intagrated the move to pose to the scoring positions
GreenBlitz/CRRRRESCENDO pull request #46
Opened 2024-01-27 14:42 UTC by YoniKiriaty

2024-01-27 15:52 UTC, tnrz135 requested changes

2024-01-27 15:52 UTC, tnrz135 commented on src/main/java/edu/greenblitz/robotName/Field.java
> +        public final static Pose2d climbPosition = new Pose2d(new Translation2d(7,2),new Rotation2d());
Those are consts, they should be UPPER_SNAKE_CASE

2024-01-27 16:04 UTC, aaa-png requested changes

2024-01-27 16:04 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToAmp.java
> +}
Yoni - scheduling in the initialize of a command is very ugly, you can probably change MoveToPose so you can extend it to move to the amp position.

2024-01-27 16:04 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToClimbPosition.java
> +}
Yoni - same here

2024-01-27 16:04 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToSpeaker.java
> +}
Yoni - triple same here

2024-01-28 14:30 UTC, greenblitz4590 approved these changes

2024-01-28 15:32 UTC, tnrz135 requested changes

2024-01-28 15:32 UTC, tnrz135 commented on src/main/java/edu/greenblitz/robotName/commands/auto/MoveToPose.java
> +public class MoveToPose extends GBCommand {
Pose (stylized as POSE) is an American drama television series about New York City's ball culture, an LGBTQ subculture in the African-American and Latino communities, throughout the 1980s and 1990s. Featured characters are dancers and models, who compete for trophies and recognition in this underground culture and who support one another in a network of chosen families known as Houses.

2024-01-28 15:36 UTC, merged