battery disabler -> master
GreenBlitz/CRRRRESCENDO pull request #5
Opened 2024-01-12 15:21 UTC by NoamRosenberg08

2024-01-14 20:06 UTC, Stormageddon37 requested changes
Small PR 🤯

2024-01-14 20:06 UTC, Stormageddon37 commented on src/main/java/edu/greenblitz/robotName/commands/swerve/Battery/BatteryLimiter.java
> +                    && DriverStation.getMatchType() == DriverStation.MatchType.None) {
Does this `MatchType.None` mean practice?

2024-01-14 20:06 UTC, Stormageddon37 commented on src/main/java/edu/greenblitz/robotName/commands/swerve/Battery/BatteryLimiter.java
> +        double currentAverageVoltage;
Why is this needed if the value is only initialized AND used inside the `if` block?

2024-01-15 16:09 UTC, greenblitz4590 requested changes

2024-01-15 16:09 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/robotName/commands/swerve/Battery/BatteryLimiter.java
> +        require(battery);
Are you sure this will work?

2024-01-15 16:29 UTC, bossyshrimp68 approved these changes

2024-01-15 16:33 UTC, merged