Scoring locatins in field
GreenBlitz/CRRRRESCENDO pull request #54
Opened 2024-01-28 16:16 UTC by greenblitz4590

2024-01-28 16:17 UTC, aaa-png approved these changes

2024-01-28 17:59 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/Field.java
let's create consts for real field and upstairs field

2024-01-28 18:03 UTC, yonnbro requested changes

2024-01-28 18:03 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/commands/GetNoteToSystem/GetToTransferNotePosition.java
not relevant to this PR. if so - move to right PR

2024-01-28 18:03 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/commands/GetNoteToSystem/MoveShooterToAngle.java
not relevant to this PR. if so - move to right PR

2024-01-28 18:36 UTC, NoamRosenberg08 requested changes

2024-01-28 18:36 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/Field.java
> +        public final static Pose2d SPEAKER_SCORE_POSITION = new Pose2d(new Translation2d(14.140,5.85),new Rotation2d());
shouldntwesaqve this as arotation2D?
if therearecoliisiton with MoveToPose add a functions for translations

2024-01-29 12:16 UTC, NoamRosenberg08 approved these changes

2024-01-29 15:45 UTC, tnrz135 approved these changes

2024-01-29 15:45 UTC, tnrz135 commented on src/main/java/edu/greenblitz/robotName/Field.java
They did it but forgot to resolve and now it is blocking the merge

2024-01-29 15:46 UTC, merged