differential shooter -> master
GreenBlitz/CRRRRESCENDO pull request #63
Opened 2024-01-30 13:18 UTC by NoamRosenberg08

2024-01-30 15:05 UTC, itamaroryan requested changes
Noam please clean up the code before PRing next time

2024-01-30 15:05 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/FlyWheel/FlyWheel.java
> +package edu.greenblitz.robotName.subsystems.Shooter.FlyWheel;
Package name convetntions!

2024-01-30 15:05 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/FlyWheel/FlyWheelConstants.java
> +package edu.greenblitz.robotName.subsystems.Shooter.FlyWheel;
Package naming conventions!

2024-01-30 15:05 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/FlyWheel/NeoFlyWheel/NeoFlyWheel.java
> +        SmartDashboard.putNumber("f l v",  NeoFlyWheelConstants.LeftMotor.FEEDFORWARD.calculate(leftVelocity));
WTF is an flv?

2024-01-30 15:05 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/Shooter/FlyWheel/NeoFlyWheel/NeoFlyWheel.java
> +        SmartDashboard.putNumber("right-voltage", rightMotor.getAppliedOutput() * Battery.getInstance().getCurrentVoltage());
Remove these

2024-02-03 12:33 UTC, YoniKiriaty reviewed
right should be right and left should be left

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
> +
spaces

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
> +            leftMotorVelocityVoltage = new VelocityVoltage(0).withEnableFOC(true);
move this or something why is this here

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
>      }
the rightPower is to the left of the leftPower
```suggestion
    public void setPower(double leftPower, double rightPower) {
        rightMotor.set(rightPower);
        leftMotor.set(leftPower);
    }
```

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
> +        leftMotor.setVoltage(leftVoltage);
same here

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
> +        leftMotor.setControl(leftMotorVelocityVoltage.withVelocity(leftVelocity));
double same here

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheel.java
> +        flyWheel.setPower(rightPower, leftPower);
triple same here

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheel.java
> +        flyWheel.setVelocity(rightVelocity, leftVelocity);
quadruple same here

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/IFlyWheel.java
> +    void setVelocity(double rightVelocity, double leftVelocity);
quintuple same here

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/NeoFlyWheel/NeoFlyWheel.java
> +    private GBSparkMax rightMotor, leftMotor;
ok im going to stop here but change all of these

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheel.java
> +        flyWheel.setPower(0,0);
```suggestion
        flyWheel.setPower(0, 0);
```

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelInputs.java
> +    public double position;
space

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/NeoFlyWheel/NeoFlyWheel.java
> +    private GBSparkMax rightMotor, leftMotor;
space

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/NeoFlyWheel/NeoFlyWheelConstants.java
> +	}
space every constant pls

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheel.java
> +    private PIDController leftMotorPIDController;
spaces

2024-02-03 12:33 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheelConstants.java
> +        public static final double J_KG_METERS_SQUARED = 1;
You mean Moment Of Inertia?

2024-02-03 13:16 UTC, bossyshrimp68 submitted a review, later dismissed

2024-02-03 13:16 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
> +    public static final double EPSILON_RPM = 0;
not 0

2024-02-03 13:16 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheel.java
> +    private double leftMotorApplied;
```suggestion
    private double rightMotorAppliedOutput;

    private double leftMotorAppliedOutput;
```

2024-02-03 13:16 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/Mechanism/ShooterMechanism.java
> +    private final MechanismLigament2d pivot;
```suggestion
    private final MechanismLigament2d pivotMechanism;
```

2024-02-03 15:31 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheel.java
> +    private double leftMotorApplied;
wait why do we even need this here

2024-02-07 18:21 UTC, roygold8 approved these changes

2024-02-07 18:36 UTC, itamaroryan requested changes

2024-02-07 18:36 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/Robot.java
> +//        Lifter.init();
Don't leave commented code

2024-02-07 18:36 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
> +        rightMotor = new TalonFX(leftMotorConstants.ID);
change to left motor ang GBTalonFXPro

2024-02-07 18:36 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/FalconPivot/FalconPivot.java
> +import static edu.greenblitz.robotName.subsystems.shooter.Pivot.MotorConstants.SWITCH_CONFIGS;
Unused imports

2024-02-07 18:36 UTC, itamaroryan commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/FalconPivot/FalconPivotConstants.java
> +import com.ctre.phoenix6.configs.MotionMagicConfigs;
Unused imports

2024-02-07 18:43 UTC, itamaroryan approved these changes

2024-02-07 18:45 UTC, merged