Yoni & Yoav - fixed moveShooterToAngle
GreenBlitz/CRRRRESCENDO pull request #71
Opened 2024-02-01 21:27 UTC by bossyshrimp68

2024-02-01 23:49 UTC, NoamRosenberg08 requested changes

2024-02-01 23:49 UTC, NoamRosenberg08 commented on simgui-ds.json
>    ]
add to .gitignore

2024-02-02 13:12 UTC, tnrz135 approved these changes

2024-02-03 10:42 UTC, NoamRosenberg08 approved these changes

2024-02-03 12:16 UTC, aaa-png approved these changes

2024-02-03 12:16 UTC, merged