Lifter cleaning
GreenBlitz/CRRRRESCENDO pull request #77
Opened 2024-02-02 14:05 UTC by YoniKiriaty

2024-02-02 14:15 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/LifterConstants.java
> +
add backward fprward limit

2024-02-02 14:15 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/NeoLifter/NeoLifter.java
> +        motor.getPIDController().setReference(position.getRadians(), CANSparkMax.ControlType.kPosition, 0 , FEED_FORWARD.calculate(position.getRadians()));
slot constant

2024-02-03 10:39 UTC, NoamRosenberg08 requested changes

2024-02-03 10:39 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/Lifter.java
> +        resetEncoder(LifterConstants.ENCODER_POSE_WHEN_RESET);
rename encoder pose to position

2024-02-03 10:39 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/Lifter.java
> +    public boolean isMotorAtPosition(Rotation2d targetPosition) {
```suggestion
      public boolean isAtPosition(Rotation2d targetPosition) {
```

2024-02-03 10:39 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/LifterConstants.java
> +    public static final double TOLERANCE = 0.04;
remember that the tolerance is an angle. consider changing the tolerance to a rotation 2d

2024-02-03 10:39 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/NeoLifter/NeoLifter.java
> +        motor.getForwardLimitSwitch(NeoLifterConstants.BACKWARD_LIMIT_SWITCH_TYPE).enableLimitSwitch(true);
for the enableLimitSwitch change the 'true' to a constant

2024-02-03 10:39 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/SimulationLifter/SimulationLifterConstants.java
>      public static final double MOMENT_OF_INERTIA = 0.03;
use the         SingleJointedArmSim.estimateMOI()  function

2024-02-03 11:04 UTC, yonnbro requested changes

2024-02-03 11:41 UTC, bossyshrimp68 approved these changes
fix everything noam said tho

2024-02-03 12:10 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/commands/lifter/ReverseLifting.java
>          lifter.stopMotor();
what?

2024-02-03 13:22 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/commands/lifter/ReverseLifting.java
>          lifter.stopMotor();
Noam was testing a hardware lock for the lifter, and I don't know if it made it to the final design... if it did we didn't add it to code, so please talk to him to make sure about it

2024-02-03 13:57 UTC, aaa-png approved these changes

2024-02-04 18:27 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/NeoLifter/NeoLifter.java
> +        motor.getReverseLimitSwitch(NeoLifterConstants.FORWARD_LIMIT_SWITCH_TYPE).enableLimitSwitch(NeoLifterConstants.IS_BACKWARD_LIMIT_SWITCH_ENABLED);
getReverseLimitSwitch recieves FORWARD_LIMIT_SWITCH_TYPE?

2024-02-04 18:27 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/Lifter/NeoLifter/NeoLifter.java
> +        motor.getForwardLimitSwitch(NeoLifterConstants.BACKWARD_LIMIT_SWITCH_TYPE).enableLimitSwitch(NeoLifterConstants.IS_FORWARD_LIMIT_SWITCH_ENABLED);
the same?

2024-02-04 18:30 UTC, tnrz135 approved these changes

2024-02-06 17:23 UTC, yonnbro approved these changes

2024-02-06 17:54 UTC, NoamRosenberg08 approved these changes

2024-02-06 17:55 UTC, merged