yoav - fixed intake funnel
GreenBlitz/CRRRRESCENDO pull request #79
Opened 2024-02-02 16:28 UTC by YoniKiriaty

2024-02-02 16:29 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntake.java
>  	public NeoIntake() {
spaces

2024-02-02 16:30 UTC, YoniKiriaty reviewed
i like me some spaces

2024-02-02 16:30 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntake.java
>  	private Debouncer exitBeamBreaker;
spaces pls

2024-02-02 16:30 UTC, YoniKiriaty commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/IntakeConstants.java
> +
spaces

2024-02-03 10:30 UTC, NoamRosenberg08 requested changes

2024-02-03 10:30 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntake.java
> +		motor.getReverseLimitSwitch(ENTRANCE_BEAM_BREAKER_TYPE).enableLimitSwitch(false);
change the 'false' to a constant

2024-02-03 10:30 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntake.java
> +		motor.getForwardLimitSwitch(EXIT_BEAM_BREAKER_TYPE).enableLimitSwitch(false);
same here

2024-02-03 10:30 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntakeConstants.java
> +            .withRampRate(RobotConstants.General.RAMP_RATE_VAL)
out of CR scope, rename RAMP_RATE_VAL to RAMP_RATE_VALUE

2024-02-03 10:48 UTC, yonnbro approved these changes
aside from noam's comments - approved

2024-02-03 11:28 UTC, bossyshrimp68 approved these changes

2024-02-03 13:07 UTC, bossyshrimp68 approved these changes

2024-02-03 13:10 UTC, yonnbro approved these changes

2024-02-03 13:29 UTC, NoamRosenberg08 approved these changes

2024-02-03 13:29 UTC, merged