Ran - Autonomous Shooting
GreenBlitz/CRRRRESCENDO pull request #84
Opened 2024-02-04 15:22 UTC by RJ0907

2024-02-04 15:44 UTC, aaa-png requested changes
ctrl + alt + l

2024-02-04 15:44 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/commands/shooter/Shoot.java
> +    public Shoot() {
not informative!!!!!~!

2024-02-04 15:44 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootAutomatically.java
> +                new Shoot()
shoot dosent shoot

2024-02-04 15:44 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheel.java
> +public class RunFlyWheel extends FlyWheelCommand {
not informative

2024-02-04 15:44 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByPowerConstant.java
same like runflywheel

2024-02-04 15:44 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/GoToShootingState.java
> +                new RunFlyWheel()
why runflywheel?

2024-02-04 15:56 UTC, RJ0907 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheel.java
> +public class RunFlyWheel extends FlyWheelCommand {
Romy chose this name

2024-02-04 15:56 UTC, RJ0907 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByPowerConstant.java
not a command I wrote

2024-02-04 15:56 UTC, RJ0907 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/GoToShootingState.java
> +                new RunFlyWheel()
again, not a command I wrote

2024-02-04 15:57 UTC, RJ0907 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/ShootAutomatically.java
> +                new Shoot()
So what does it do if it doesnt shoot?

2024-02-04 15:57 UTC, RJ0907 commented on src/main/java/edu/greenblitz/robotName/commands/shooter/Shoot.java
> +    public Shoot() {
not a command I wrote

2024-02-04 18:31 UTC, bossyshrimp68 requested changes
stopped in the middle, waiting for the shooting command merge DO NOT CR THIS

2024-02-04 18:31 UTC, bossyshrimp68 commented on simgui-ds.json
delete

2024-02-04 18:31 UTC, bossyshrimp68 commented on simgui.json
delete

2024-02-04 18:31 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Field.java
> +    public static class PositionsToShootAutomaticallyFrom{
```suggestion
    public static class AutonomousShootingPositions{
```

2024-02-04 18:31 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/robotName/Field.java
> +        //The values are random
before merge find

2024-02-06 17:00 UTC, yonnbro commented
אני מבקש לא לפתוח PRים אם לא צריך לעבור עליהם, אפשר להשאיר את הPR כdraft ואז עדיין אפשר לעבור על הקוד אבל זה לא יהיה ברשימת PRים

2024-02-07 22:08 UTC, closed without merging