Fix pivot
GreenBlitz/CRRRRESCENDO pull request #86
Opened 2024-02-05 11:10 UTC by greenblitz4590

2024-02-05 15:49 UTC, aaa-png requested changes

2024-02-05 15:49 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/OI.java
> +        secondJoystick.Y.onTrue(new MovePivotToAngle(PivotConstants.PresetPositions.SAFE.ANGLE));
delete when merge

2024-02-05 15:49 UTC, aaa-png commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/SimulationPivot/SimulationPivot.java
> +
add setPower(0)

2024-02-06 11:04 UTC, aaa-png approved these changes

2024-02-06 13:44 UTC, yonnbro commented on src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/Pivot.java
> +				new Rotation3d(getAngle().getRadians() - SimulationPivotConstants.MECHANISM_NAME_TO_ROBOT_TRANSLATION.getRadians(), 0, 0)
לא הבנתי, כתבתם שצריך את זה פה אבל בסוף שינתם?

2024-02-06 13:45 UTC, yonnbro approved these changes

2024-02-06 14:01 UTC, merged